# Global LLM configuration
[llm]
model = "deepseek-reasoner"
base_url = "https://api.deepseek.com"
api_key = "sk-908ab67cb57d40bd88c33f941979ae9d"
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "deepseek-reasoner"
base_url = "https://api.deepseek.com"
api_key = "sk-908ab67cb57d40bd88c33f941979ae9d"
